
services:

  otter:
    build:
      context: ../../
      dockerfile: examples/cluster/Dockerfile
    container_name: otter
    ports:
      - "8080:8080"
      - "8089:8089"
    depends_on:
      - dgraph-alpha
    environment:
      CONFIG_FILE: /app/manifest/config.yaml
    volumes:
      - ../../manifest/config_docker.yaml:/app/manifest/config.yaml
    working_dir: /app
    command: ./otter

  dgraph-zero:
    image: dgraph/dgraph:latest
    container_name: dgraph-zero-otter
    ports:
      - "5080:5080"
      - "6080:6080"
    volumes:
      - dgraph-zero-otter:/dgraph
    command: dgraph zero --my=dgraph-zero:5080

  dgraph-alpha:
    image: dgraph/dgraph:latest
    container_name: dgraph-alpha-otter
    ports:
      - "8081:8081"
      - "9081:9081"
    volumes:
      - dgraph-alpha-otter:/dgraph
    depends_on:
      - dgraph-zero
    command: >
      dgraph alpha
      -p /dgraph/p1
      -w /dgraph/w1
      --my=dgraph-alpha:7081
      --zero=dgraph-zero:5080
      --security whitelist=0.0.0.0/0
      -o 1

  dgraph-alpha2:
    image: dgraph/dgraph:latest
    container_name: dgraph-alpha-otter2
    ports:
      - "8082"
      - "9082"
    volumes:
      - dgraph-alpha-otter:/dgraph
    depends_on:
      - dgraph-zero
    command: >
      dgraph alpha
      -p /dgraph/p2
      -w /dgraph/w2
      --my=dgraph-alpha2:7082
      --zero=dgraph-zero:5080
      --security whitelist=0.0.0.0/0
      -o 2

  dgraph-alpha3:
    image: dgraph/dgraph:latest
    container_name: dgraph-alpha-otter3
    ports:
      - "8083"
      - "9083"
    volumes:
      - dgraph-alpha-otter:/dgraph
    depends_on:
      - dgraph-zero
    command: >
      dgraph alpha
      -p /dgraph/p3
      -w /dgraph/w3
      --my=dgraph-alpha3:7083
      --zero=dgraph-zero:5080
      --security whitelist=0.0.0.0/0
      -o 3


volumes:
  dgraph-zero-otter:
  dgraph-alpha-otter:
