balancer_type: defined
proxy_port: 8084
websocket_port: 8089
dgraph_user: ""
dgraph_password: ""
enable_http: true
enable_websocket: true
dgraph_endpoints: # Needed if using simple round-robin balancing
  - dgraph-alpha1:9081
  - dgraph-alpha2:9082
groups:
  query:
    - dgraph-alpha1:9081
    - dgraph-alpha2:9082
  mutation:
    - dgraph-alpha3:9083
  upsert:
    - dgraph-alpha3:9083
    - dgraph-alpha2:9082
