on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binaries (make release)
        run: make release

      - name: Check if it's a prerelease
        id: prerelease
        run: |
          if [[ "${GITHUB_REF##*/}" == *"-beta"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  